### ISSUE TITLE
Hi I face error when I run firebase deploy --only functions.

### ISSUE THREAD

**Issue by chewszeqi** [nicolaa5/covidtracer#13]

**Comment by chewszeqi** [comment]
![image](https://user-images.githubusercontent.com/72686940/110445247-e197d180-80f8-11eb-9fd7-a01971db17a4.png)
![image](https://user-images.githubusercontent.com/72686940/110445340-f5dbce80-80f8-11eb-9d87-e2edca0a9ff9.png)
![image](https://user-images.githubusercontent.com/72686940/110445550-32a7c580-80f9-11eb-8142-017b6143eb7a.png)
![image](https://user-images.githubusercontent.com/72686940/110445657-4f43fd80-80f9-11eb-8cf4-98ecd2d3087c.png)

**Comment by nicolaa5** [comment]
Hi chewszeqi, it could be that you don't have `eslint` installed.
When running `firebase init functions` you're asked the following: 

_Do you want to use ESLint to catch probable bugs and enforce style?_ 

You can run `firebase init functions` again to reinitialize and enable this setting, or remove `eslint` checks and devDependencies in `firestore/functions/package.json` if you don't want to use linting.

Here's someone else's issue description who ran into the same problem: https://stackoverflow.com/questions/59337001/firebase-function-predeploy-error-command-terminated-with-non-zero-exit-code1

**Comment by chewszeqi** [comment]
I solved the issue!!Thank you very much. I would like to ask about the json schema for firebase. Is it related to the google-services json obtained when we add firebase to our android app?

**Comment by chewszeqi** [comment]
When I tried to register with the testing phone number set in firebase, it returned to the previous page, which is activity_main.xml. Do you know how to solve the issue?

**Comment by nicolaa5** [comment]
Hey @chewszeqi, do you mean the json schema in `firebase.json`? Here you can specify the settings for deploying services such as Firebase functions. The `google-services.json` contains all your important private Firebase API settings and credentials.

You can replace the testing phone number and country prefix `+46` with your own prefix and number. Returning to the _activity_main.xml_ page sounds like the intended behaviour after registering. If you have a specific error or function to look at related to the phone number registration you can create a new issue here or in the [original repository](https://github.com/alexandrumeterez/covidtracer). I will see if I can help out with questions but there might be more people who can help you there:)
